### ISSUE TITLE
any idea on Opencore version?

### ISSUE THREAD

**Issue by digbit** [dezinezync/X299-EFI-Folder-Distributions#1]
Many thanks for your clover EFI !

I wonder if you consider releasing an Opencore version ?

Refs:

https://www.tonymacx86.com/threads/x299-open-core-support.282158/

https://github.com/shinoki7/Asus-X299-Hackintosh/tree/master/OpenCore-EFI-Distributions/ASUS

**Comment by dezinezync** [comment]
@digbit Interesting idea. I'll look into this and maintain two separate folders, one for each.

**Comment by digbit** [comment]
Hi Dezinezync,

I have switched to OC now. you can have a try.

My computer's spec is the same as yours.

[https://github.com/digbit/x299-opencore-hackintosh](url)

**Comment by dezinezync** [comment]
That's awesome. Let me try that and get back to you.

**Comment by dezinezync** [comment]
@digbit I tried your release but it didn't work for me. however, I was able to use your config as a base and have both 10.15.6 and 11.0 Beta 5 working. Will update this repo once I have all PCI devices mapped.

**Comment by dezinezync** [comment]
Added OC Dist. in https://github.com/dezinezync/X299-EFI-Folder-Distributions/commit/515a1eb5ff214205d8d04d47e83e1a66d3e7cbee
