### ISSUE TITLE
Does this EFI support the NEWEST BIOS v3403？

### ISSUE THREAD

**Issue by wmjlxl** [dezinezync/X299-EFI-Folder-Distributions#5]
hello，

first thanks for sharing.

i have one issue, if you upgrade BIOS to 3403.
macos cannot boot anymore.

do you have the same issue?

bios 3403 has resize-bar support, so i want to upgrade it.

**Comment by dezinezync** [comment]
Hi, I haven't tested against this BIOS version. I'm still on the 08XX version.

**Comment by dezinezync** [comment]
What the error you are seeing?

**Comment by wmjlxl** [comment]
i cannot boot into macos if i use the newest bios 3403.

may be you can have a try.

**Comment by dezinezync** [comment]
Do you see any errors on screen? Can you post a screenshot?

**Comment by wmjlxl** [comment]
what a pity, i didnt captureeur it last night....

**Comment by dezinezync** [comment]
Next time you try, please take a photo or screenshot and post here. 

You can also try disabling all ACPI patches until installation, and enable them one by one after installation. 

Some ACPI patches are necessary for the installer to boot. Refer to the OpenCore docs.

**Comment by wmjlxl** [comment]
i tried bios 3403 again last night with no luck.

yes, i disabled all acpi patches.

attached log file fyi.

[opencore-2021-04-06-151221.txt](https://github.com/dezinezync/X299-EFI-Folder-Distributions/files/6268494/opencore-2021-04-06-151221.txt)

**Comment by dezinezync** [comment]
1. I noticed you have a 9920X. Please updated the TSC kext’s Info.plist for 12 cores instead of the 14 of my 9940X. 

2. Try disabling the USB kext. Use the top most USB ports on the rear of the motherboard for installation.

**Comment by wmjlxl** [comment]
In fact, I have already done with no luck.... 

I plan to give up upgrading the BIOS。。。

**Comment by dezinezync** [comment]
@wmjlxl What GPU are you using?

**Comment by wmjlxl** [comment]
RX 560 without any problem if i use BIOS 0802

**Comment by dezinezync** [comment]
@wmjlxl that's supported out of the box. Have you also disabled my 5700XT ACPI Patch? Please confirm. 

Try: 
1. My Clover Dist has a RX580 ACPI patch which you should be able to adapt

OR

2. Add and enable the latest Lilu.kext and WhateverGreen.kext

**Comment by wmjlxl** [comment]
thanks for your help really.

i tried everything but with no luck

i plan to give up now.
