### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by diyqsxl** [dezinezync/X299-EFI-Folder-Distributions#6]
你好。使用您的efi引导11.5.1的时候貌似卡在USB上。请问能否提供bios设置截图 ！这将非常感谢

**Comment by dezinezync** [comment]
No special BIOS settings for USB. 

Are you using the same board as me? (Asus X299 Deluxe II) If not, you'll have to do port mapping specific to your board. 

Even with the same board, it is good to inspect the port mapping in the USB kext as we may be using different USB3.0 headers. 

For first boot, avoid using the USB3.0 ports if possible.
