### ISSUE TITLE
新的bios怎样设置才能支持雷电

### ISSUE THREAD

**Issue by DT-CHC** [dezinezync/X299-EFI-Folder-Distributions#7]
新的bios设置备份文件能提供下吗。然后就是雷电。能驱动吗？
是否支持 热插拔

**Comment by dezinezync** [comment]
Hotplug not supported directly. Need to boot with a TB3 device plugged in to any TB3 port. After that, hot plug works. 

BIOS Settings same as this guide: https://www.tonymacx86.com/threads/imac-pro-x299-live-the-future-now-with-macos-10-14-mojave-successful-build-extended-guide.255082/
